import React, { Component } from 'react'
import request from 'superagent';

export default class ImportsMunicipios extends Component {


componentDidMount(){
    //this.listarMunicipios();
    this.listarDepartamentos();

}

  addMunicipio(id, nombre, codDep){

        request
            .post('/response/empresas/registro/addMunicipio')
            .send({ id: id, nombre: nombre,  codDep: codDep}) // sends a JSON post body
            .set('accept', 'json')
            .end((err, res) => {
                    
                if (err) {
                    console.log("No agregado ERROR : "+id)
                } else {

                }


            });

    }

    addDepartamentos(id, codigo, nombre){

        request
            .post('/response/empresas/registro/addDepartamento')
            .send({ id: id, codigo: codigo, nombre: nombre}) // sends a JSON post body
            .set('accept', 'json')
            .end((err, res) => {
                    
                if (err) {
                    console.log("No agregado ERROR : "+id)
                } else {

                }


            });

    }

    listarMunicipios(){
        municipios.map((item) => {
            this.addMunicipio(item.id, item.nombre, item.codDep);
        })
    }

    listarDepartamentos(){
        departamentos.map((item) => {
            this.addDepartamentos(item.id, item.codigo, item.nombre);
        })
    }


    render() {
        return (
            <div>
                okokok
            </div>
        )
    }
}

const departamentos = [
    { "id": 1, "codigo": 5, "nombre" : "Antioquia" },
{ "id": 2, "codigo": 8, "nombre" : "Atlantico" },
{ "id": 3, "codigo": 11, "nombre" : "Santa Fe de Bogotá" },
{ "id": 4, "codigo": 13, "nombre" : "Bolivar" },
{ "id": 5, "codigo": 15, "nombre" : "Boyacá" },
{ "id": 6, "codigo": 17, "nombre" : "Caldas" },
{ "id": 7, "codigo": 18, "nombre" : "Caqueta" },
{ "id": 8, "codigo": 19, "nombre" : "Cauca" },
{ "id": 9, "codigo": 20, "nombre" : "Cesar" },
{ "id": 10, "codigo": 23, "nombre" : "Cordova" },
{ "id": 11, "codigo": 25, "nombre" : "Cundinamarca" },
{ "id": 12, "codigo": 27, "nombre" : "Choco" },
{ "id": 13, "codigo": 41, "nombre" : "Huila" },
{ "id": 14, "codigo": 44, "nombre" : "La Guajira" },
{ "id": 15, "codigo": 47, "nombre" : "Magdalena" },
{ "id": 16, "codigo": 50, "nombre" : "Meta" },
{ "id": 17, "codigo": 52, "nombre" : "Nariño" },
{ "id": 18, "codigo": 54, "nombre" : "Norte de Santander" },
{ "id": 19, "codigo": 63, "nombre" : "Quindio" },
{ "id": 20, "codigo": 66, "nombre" : "Risaralda" },
{ "id": 21, "codigo": 68, "nombre" : "Santander" },
{ "id": 22, "codigo": 70, "nombre" : "Sucre" },
{ "id": 23, "codigo": 73, "nombre" : "Tolima" },
{ "id": 24, "codigo": 76, "nombre" : "Valle" },
{ "id": 25, "codigo": 81, "nombre" : "Arauca" },
{ "id": 26, "codigo": 85, "nombre" : "Casanare" },
{ "id": 27, "codigo": 86, "nombre" : "Putumayo" },
{ "id": 28, "codigo": 88, "nombre" : "San Andres" },
{ "id": 29, "codigo": 91, "nombre" : "Amazonas" },
{ "id": 30, "codigo": 94, "nombre" : "Guainia" },
{ "id": 31, "codigo": 95, "nombre" : "Guaviare" },
{ "id": 32, "codigo": 97, "nombre" : "Vaupes" },
{ "id": 33, "codigo": 99, "nombre" : "Vichada" },
]

const municipios = [
    { "id": 1, "nombre": "MEDELLIN","codDep": 5},
{ "id": 2, "nombre": "ABEJORRAL","codDep": 5},
{ "id": 3, "nombre": "ABRIAQUI","codDep": 5},
{ "id": 4, "nombre": "ALEJANDRIA","codDep": 5},
{ "id": 5, "nombre": "AMAGA","codDep": 5},
{ "id": 6, "nombre": "AMALFI","codDep": 5},
{ "id": 7, "nombre": "ANDES","codDep": 5},
{ "id": 8, "nombre": "ANGELOPOLIS","codDep": 5},
{ "id": 9, "nombre": "ANGOSTURA","codDep": 5},
{ "id": 10, "nombre": "ANORI","codDep": 5},
{ "id": 11, "nombre": "ANTIOQUIA","codDep": 5},
{ "id": 12, "nombre": "ANZA","codDep": 5},
{ "id": 13, "nombre": "APARTADO","codDep": 5},
{ "id": 14, "nombre": "ARBOLETES","codDep": 5},
{ "id": 15, "nombre": "ARGELIA","codDep": 5},
{ "id": 16, "nombre": "ARMENIA","codDep": 5},
{ "id": 17, "nombre": "BARBOSA","codDep": 5},
{ "id": 18, "nombre": "BELMIRA","codDep": 5},
{ "id": 19, "nombre": "BELLO","codDep": 5},
{ "id": 20, "nombre": "BETANIA","codDep": 5},
{ "id": 21, "nombre": "BETULIA","codDep": 5},
{ "id": 22, "nombre": "BOLIVAR","codDep": 5},
{ "id": 23, "nombre": "BRICEÑO","codDep": 5},
{ "id": 24, "nombre": "BURITICA","codDep": 5},
{ "id": 25, "nombre": "CACERES","codDep": 5},
{ "id": 26, "nombre": "CAICEDO","codDep": 5},
{ "id": 27, "nombre": "CALDAS","codDep": 5},
{ "id": 28, "nombre": "CAMPAMENTO","codDep": 5},
{ "id": 29, "nombre": "CAÑASGORDAS","codDep": 5},
{ "id": 30, "nombre": "CARACOLI","codDep": 5},
{ "id": 31, "nombre": "CARAMANTA","codDep": 5},
{ "id": 32, "nombre": "CAREPA","codDep": 5},
{ "id": 33, "nombre": "CARMEN DE VIBORAL","codDep": 5},
{ "id": 34, "nombre": "CAROLINA","codDep": 5},
{ "id": 35, "nombre": "CAUCASIA","codDep": 5},
{ "id": 36, "nombre": "CHIGORODO","codDep": 5},
{ "id": 37, "nombre": "CISNEROS","codDep": 5},
{ "id": 38, "nombre": "COCORNA","codDep": 5},
{ "id": 39, "nombre": "CONCEPCION","codDep": 5},
{ "id": 40, "nombre": "CONCORDIA","codDep": 5},
{ "id": 41, "nombre": "COPACABANA","codDep": 5},
{ "id": 42, "nombre": "DABEIBA","codDep": 5},
{ "id": 43, "nombre": "DON MATIAS","codDep": 5},
{ "id": 44, "nombre": "EBEJICO","codDep": 5},
{ "id": 45, "nombre": "EL BAGRE","codDep": 5},
{ "id": 46, "nombre": "ENTRERRIOS","codDep": 5},
{ "id": 47, "nombre": "ENVIGADO","codDep": 5},
{ "id": 48, "nombre": "FREDONIA","codDep": 5},
{ "id": 49, "nombre": "FRONTINO","codDep": 5},
{ "id": 50, "nombre": "GIRALDO","codDep": 5},
{ "id": 51, "nombre": "GIRARDOTA","codDep": 5},
{ "id": 52, "nombre": "GOMEZ PLATA","codDep": 5},
{ "id": 53, "nombre": "GRANADA","codDep": 5},
{ "id": 54, "nombre": "GUADALUPE","codDep": 5},
{ "id": 55, "nombre": "GUARNE","codDep": 5},
{ "id": 56, "nombre": "GUATAPE","codDep": 5},
{ "id": 57, "nombre": "HELICONIA","codDep": 5},
{ "id": 58, "nombre": "HISPANIA","codDep": 5},
{ "id": 59, "nombre": "ITAGUI","codDep": 5},
{ "id": 60, "nombre": "ITUANGO","codDep": 5},
{ "id": 61, "nombre": "JARDIN","codDep": 5},
{ "id": 62, "nombre": "JERICO","codDep": 5},
{ "id": 63, "nombre": "LA CEJA","codDep": 5},
{ "id": 64, "nombre": "LA ESTRELLA","codDep": 5},
{ "id": 65, "nombre": "LA PINTADA","codDep": 5},
{ "id": 66, "nombre": "LA UNION","codDep": 5},
{ "id": 67, "nombre": "LIBORINA","codDep": 5},
{ "id": 68, "nombre": "MACEO","codDep": 5},
{ "id": 69, "nombre": "MARINILLA","codDep": 5},
{ "id": 70, "nombre": "MONTEBELLO","codDep": 5},
{ "id": 71, "nombre": "MURINDO","codDep": 5},
{ "id": 72, "nombre": "MUTATA","codDep": 5},
{ "id": 73, "nombre": "NARIÑO","codDep": 5},
{ "id": 74, "nombre": "NECOCLI","codDep": 5},
{ "id": 75, "nombre": "NECHI","codDep": 5},
{ "id": 76, "nombre": "OLAYA","codDep": 5},
{ "id": 77, "nombre": "PEÑOL","codDep": 5},
{ "id": 78, "nombre": "PEQUE","codDep": 5},
{ "id": 79, "nombre": "PUEBLORRICO","codDep": 5},
{ "id": 80, "nombre": "PUERTO BERRIO","codDep": 5},
{ "id": 81, "nombre": "PUERTO NARE LA MAGDALENA","codDep": 5},
{ "id": 82, "nombre": "PUERTO TRIUNFO","codDep": 5},
{ "id": 83, "nombre": "REMEDIOS","codDep": 5},
{ "id": 84, "nombre": "RETIRO","codDep": 5},
{ "id": 85, "nombre": "RIONEGRO","codDep": 5},
{ "id": 86, "nombre": "SABANALARGA","codDep": 5},
{ "id": 87, "nombre": "SABANETA","codDep": 5},
{ "id": 88, "nombre": "SALGAR","codDep": 5},
{ "id": 89, "nombre": "SAN ANDRES","codDep": 5},
{ "id": 90, "nombre": "SAN CARLOS","codDep": 5},
{ "id": 91, "nombre": "SAN FRANCISCO","codDep": 5},
{ "id": 92, "nombre": "SAN JERONIMO","codDep": 5},
{ "id": 93, "nombre": "SAN JOSE DE LA MONTAÑA","codDep": 5},
{ "id": 94, "nombre": "SAN JUAN DE URABA","codDep": 5},
{ "id": 95, "nombre": "SAN LUIS","codDep": 5},
{ "id": 96, "nombre": "SAN PEDRO","codDep": 5},
{ "id": 97, "nombre": "SAN PEDRO DE URABA","codDep": 5},
{ "id": 98, "nombre": "SAN RAFAEL","codDep": 5},
{ "id": 99, "nombre": "SAN ROQUE","codDep": 5},
{ "id": 100, "nombre": "SAN VICENTE","codDep": 5},
{ "id": 101, "nombre": "SANTA BARBARA","codDep": 5},
{ "id": 102, "nombre": "SANTA ROSA DE OSOS","codDep": 5},
{ "id": 103, "nombre": "SANTO DOMINGO","codDep": 5},
{ "id": 104, "nombre": "SANTUARIO","codDep": 5},
{ "id": 105, "nombre": "SEGOVIA","codDep": 5},
{ "id": 106, "nombre": "SONSON","codDep": 5},
{ "id": 107, "nombre": "SOPETRAN","codDep": 5},
{ "id": 108, "nombre": "TAMESIS","codDep": 5},
{ "id": 109, "nombre": "TARAZA","codDep": 5},
{ "id": 110, "nombre": "TARSO","codDep": 5},
{ "id": 111, "nombre": "TITIRIBI","codDep": 5},
{ "id": 112, "nombre": "TOLEDO","codDep": 5},
{ "id": 113, "nombre": "TURBO","codDep": 5},
{ "id": 114, "nombre": "URAMITA","codDep": 5},
{ "id": 115, "nombre": "URRAO","codDep": 5},
{ "id": 116, "nombre": "VALDIVIA","codDep": 5},
{ "id": 117, "nombre": "VALPARAISO","codDep": 5},
{ "id": 118, "nombre": "VEGACHI","codDep": 5},
{ "id": 119, "nombre": "VENECIA","codDep": 5},
{ "id": 120, "nombre": "VIGIA DEL FUERTE","codDep": 5},
{ "id": 121, "nombre": "YALI","codDep": 5},
{ "id": 122, "nombre": "YARUMAL","codDep": 5},
{ "id": 123, "nombre": "YOLOMBO","codDep": 5},
{ "id": 124, "nombre": "YONDO","codDep": 5},
{ "id": 125, "nombre": "ZARAGOZA","codDep": 5},
{ "id": 126, "nombre": "BARRANQUILLA","codDep": 8},
{ "id": 127, "nombre": "BARANOA","codDep": 8},
{ "id": 128, "nombre": "CAMPO DE LA CRUZ","codDep": 8},
{ "id": 129, "nombre": "CANDELARIA","codDep": 8},
{ "id": 130, "nombre": "GALAPA","codDep": 8},
{ "id": 131, "nombre": "JUAN DE ACOSTA","codDep": 8},
{ "id": 132, "nombre": "LURUACO","codDep": 8},
{ "id": 133, "nombre": "MALAMBO","codDep": 8},
{ "id": 134, "nombre": "MANATI","codDep": 8},
{ "id": 135, "nombre": "PALMAR DE VARELA","codDep": 8},
{ "id": 136, "nombre": "PIOJO","codDep": 8},
{ "id": 137, "nombre": "POLO NUEVO","codDep": 8},
{ "id": 138, "nombre": "PONEDERA","codDep": 8},
{ "id": 139, "nombre": "PUERTO COLOMBIA","codDep": 8},
{ "id": 140, "nombre": "REPELON","codDep": 8},
{ "id": 141, "nombre": "SABANAGRANDE","codDep": 8},
{ "id": 142, "nombre": "SABANALARGA","codDep": 8},
{ "id": 143, "nombre": "SANTA LUCIA","codDep": 8},
{ "id": 144, "nombre": "SANTO TOMAS","codDep": 8},
{ "id": 145, "nombre": "SOLEDAD","codDep": 8},
{ "id": 146, "nombre": "SUAN","codDep": 8},
{ "id": 147, "nombre": "TUBARA","codDep": 8},
{ "id": 148, "nombre": "USIACURI","codDep": 8},
{ "id": 149, "nombre": "SANTA FE DE BOGOTA, D. C.","codDep": 11},
{ "id": 150, "nombre": "SANTAFE DE BOGOTA D.C.-USAQUEN","codDep": 11},
{ "id": 151, "nombre": "SANTAFE DE BOGOTA D.C.-CHAPINERO","codDep": 11},
{ "id": 152, "nombre": "SANTAFE DE BOGOTA D.C.-SANTA FE","codDep": 11},
{ "id": 153, "nombre": "SANTAFE DE BOGOTA D.C.-SAN CRISTOBAL","codDep": 11},
{ "id": 154, "nombre": "SANTAFE DE BOGOTA D.C.-USME","codDep": 11},
{ "id": 155, "nombre": "SANTAFE DE BOGOTA D.C.-TUNJUELITO","codDep": 11},
{ "id": 156, "nombre": "SANTAFE DE BOGOTA D.C.-BOSA","codDep": 11},
{ "id": 157, "nombre": "SANTAFE DE BOGOTA D.C.-KENNEDY","codDep": 11},
{ "id": 158, "nombre": "SANTAFE DE BOGOTA D.C.-FONTIBON","codDep": 11},
{ "id": 159, "nombre": "SANTAFE DE BOGOTA D.C.-ENGATIVA","codDep": 11},
{ "id": 160, "nombre": "SANTAFE DE BOGOTA D.C.-SUBA","codDep": 11},
{ "id": 161, "nombre": "SANTAFE DE BOGOTA D.C.-BARRIOS UNIDOS","codDep": 11},
{ "id": 162, "nombre": "SANTAFE DE BOGOTA D.C.-TEUSAQUILLO","codDep": 11},
{ "id": 163, "nombre": "SANTAFE DE BOGOTA D.C.-MARTIRES","codDep": 11},
{ "id": 164, "nombre": "SANTAFE DE BOGOTA D.C.-ANTONIO NARIÑO","codDep": 11},
{ "id": 165, "nombre": "SANTAFE DE BOGOTA D.C.-PUENTE ARANDA","codDep": 11},
{ "id": 166, "nombre": "SANTAFE DE BOGOTA D.C.-CANDELARIA","codDep": 11},
{ "id": 167, "nombre": "SANTAFE DE BOGOTA D.C.-RAFAEL URIBE","codDep": 11},
{ "id": 168, "nombre": "SANTAFE DE BOGOTA D.C.-CIUDAD BOLIVAR","codDep": 11},
{ "id": 169, "nombre": "SANTAFE DE BOGOTA D.C.-SUMAPAZ","codDep": 11},
{ "id": 170, "nombre": "CARTAGENA","codDep": 13},
{ "id": 171, "nombre": "ACHI","codDep": 13},
{ "id": 172, "nombre": "ALTOS DEL ROSARIO","codDep": 13},
{ "id": 173, "nombre": "ARENAL","codDep": 13},
{ "id": 174, "nombre": "ARJONA","codDep": 13},
{ "id": 175, "nombre": "ARROYOHONDO","codDep": 13},
{ "id": 176, "nombre": "BARRANCO DE LOBA","codDep": 13},
{ "id": 177, "nombre": "CALAMAR","codDep": 13},
{ "id": 178, "nombre": "CANTAGALLO","codDep": 13},
{ "id": 179, "nombre": "CICUCO","codDep": 13},
{ "id": 180, "nombre": "CORDOBA","codDep": 13},
{ "id": 181, "nombre": "CLEMENCIA","codDep": 13},
{ "id": 182, "nombre": "EL CARMEN DE BOLIVAR","codDep": 13},
{ "id": 183, "nombre": "EL GUAMO","codDep": 13},
{ "id": 184, "nombre": "EL PEÑON","codDep": 13},
{ "id": 185, "nombre": "HATILLO DE LOBA","codDep": 13},
{ "id": 186, "nombre": "MAGANGUE","codDep": 13},
{ "id": 187, "nombre": "MAHATES","codDep": 13},
{ "id": 188, "nombre": "MARGARITA","codDep": 13},
{ "id": 189, "nombre": "MARIA LA BAJA","codDep": 13},
{ "id": 190, "nombre": "MONTECRISTO","codDep": 13},
{ "id": 191, "nombre": "MOMPOS","codDep": 13},
{ "id": 192, "nombre": "MORALES","codDep": 13},
{ "id": 193, "nombre": "PINILLOS","codDep": 13},
{ "id": 194, "nombre": "REGIDOR","codDep": 13},
{ "id": 195, "nombre": "RIO VIEJO","codDep": 13},
{ "id": 196, "nombre": "SAN CRISTOBAL","codDep": 13},
{ "id": 197, "nombre": "SAN ESTANISLAO","codDep": 13},
{ "id": 198, "nombre": "SAN FERNANDO","codDep": 13},
{ "id": 199, "nombre": "SAN JACINTO","codDep": 13},
{ "id": 200, "nombre": "SAN JACINTO DEL CAUCA","codDep": 13},
{ "id": 201, "nombre": "SAN JUAN NEPOMUCENO","codDep": 13},
{ "id": 202, "nombre": "SAN MARTIN DE LOBA","codDep": 13},
{ "id": 203, "nombre": "SAN PABLO","codDep": 13},
{ "id": 204, "nombre": "SANTA CATALINA","codDep": 13},
{ "id": 205, "nombre": "SANTA ROSA","codDep": 13},
{ "id": 206, "nombre": "SANTA ROSA DEL SUR","codDep": 13},
{ "id": 207, "nombre": "SIMITI","codDep": 13},
{ "id": 208, "nombre": "SOPLAVIENTO","codDep": 13},
{ "id": 209, "nombre": "TALAIGUA NUEVO","codDep": 13},
{ "id": 210, "nombre": "TIQUISIO (PUERTO RICO)","codDep": 13},
{ "id": 211, "nombre": "TURBACO","codDep": 13},
{ "id": 212, "nombre": "TURBANA","codDep": 13},
{ "id": 213, "nombre": "VILLANUEVA","codDep": 13},
{ "id": 214, "nombre": "ZAMBRANO","codDep": 13},
{ "id": 215, "nombre": "TUNJA","codDep": 15},
{ "id": 216, "nombre": "ALMEIDA","codDep": 15},
{ "id": 217, "nombre": "AQUITANIA","codDep": 15},
{ "id": 218, "nombre": "ARCABUCO","codDep": 15},
{ "id": 219, "nombre": "BELEN","codDep": 15},
{ "id": 220, "nombre": "BERBEO","codDep": 15},
{ "id": 221, "nombre": "BETEITIVA","codDep": 15},
{ "id": 222, "nombre": "BOAVITA","codDep": 15},
{ "id": 223, "nombre": "BOYACA","codDep": 15},
{ "id": 224, "nombre": "BRICEÑO","codDep": 15},
{ "id": 225, "nombre": "BUENAVISTA","codDep": 15},
{ "id": 226, "nombre": "BUSBANZA","codDep": 15},
{ "id": 227, "nombre": "CALDAS","codDep": 15},
{ "id": 228, "nombre": "CAMPOHERMOSO","codDep": 15},
{ "id": 229, "nombre": "CERINZA","codDep": 15},
{ "id": 230, "nombre": "CHINAVITA","codDep": 15},
{ "id": 231, "nombre": "CHIQUINQUIRA","codDep": 15},
{ "id": 232, "nombre": "CHISCAS","codDep": 15},
{ "id": 233, "nombre": "CHITA","codDep": 15},
{ "id": 234, "nombre": "CHITARAQUE","codDep": 15},
{ "id": 235, "nombre": "CHIVATA","codDep": 15},
{ "id": 236, "nombre": "CIENEGA","codDep": 15},
{ "id": 237, "nombre": "COMBITA","codDep": 15},
{ "id": 238, "nombre": "COPER","codDep": 15},
{ "id": 239, "nombre": "CORRALES","codDep": 15},
{ "id": 240, "nombre": "COVARACHIA","codDep": 15},
{ "id": 241, "nombre": "CUBARA","codDep": 15},
{ "id": 242, "nombre": "CUCAITA","codDep": 15},
{ "id": 243, "nombre": "CUITIVA","codDep": 15},
{ "id": 244, "nombre": "CHIQUIZA","codDep": 15},
{ "id": 245, "nombre": "CHIVOR","codDep": 15},
{ "id": 246, "nombre": "DUITAMA","codDep": 15},
{ "id": 247, "nombre": "EL COCUY","codDep": 15},
{ "id": 248, "nombre": "EL ESPINO","codDep": 15},
{ "id": 249, "nombre": "FIRAVITOBA","codDep": 15},
{ "id": 250, "nombre": "FLORESTA","codDep": 15},
{ "id": 251, "nombre": "GACHANTIVA","codDep": 15},
{ "id": 252, "nombre": "GAMEZA","codDep": 15},
{ "id": 253, "nombre": "GARAGOA","codDep": 15},
{ "id": 254, "nombre": "GUACAMAYAS","codDep": 15},
{ "id": 255, "nombre": "GUATEQUE","codDep": 15},
{ "id": 256, "nombre": "GUAYATA","codDep": 15},
{ "id": 257, "nombre": "GUICAN","codDep": 15},
{ "id": 258, "nombre": "IZA","codDep": 15},
{ "id": 259, "nombre": "JENESANO","codDep": 15},
{ "id": 260, "nombre": "JERICO","codDep": 15},
{ "id": 261, "nombre": "LABRANZAGRANDE","codDep": 15},
{ "id": 262, "nombre": "LA CAPILLA","codDep": 15},
{ "id": 263, "nombre": "LA VICTORIA","codDep": 15},
{ "id": 264, "nombre": "LA UVITA","codDep": 15},
{ "id": 265, "nombre": "VILLA DE LEIVA","codDep": 15},
{ "id": 266, "nombre": "MACANAL","codDep": 15},
{ "id": 267, "nombre": "MARIPI","codDep": 15},
{ "id": 268, "nombre": "MIRAFLORES","codDep": 15},
{ "id": 269, "nombre": "MONGUA","codDep": 15},
{ "id": 270, "nombre": "MONGUI","codDep": 15},
{ "id": 271, "nombre": "MONIQUIRA","codDep": 15},
{ "id": 272, "nombre": "MOTAVITA","codDep": 15},
{ "id": 273, "nombre": "MUZO","codDep": 15},
{ "id": 274, "nombre": "NOBSA","codDep": 15},
{ "id": 275, "nombre": "NUEVO COLON","codDep": 15},
{ "id": 276, "nombre": "OICATA","codDep": 15},
{ "id": 277, "nombre": "OTANCHE","codDep": 15},
{ "id": 278, "nombre": "PACHAVITA","codDep": 15},
{ "id": 279, "nombre": "PAEZ","codDep": 15},
{ "id": 280, "nombre": "PAIPA","codDep": 15},
{ "id": 281, "nombre": "PAJARITO","codDep": 15},
{ "id": 282, "nombre": "PANQUEBA","codDep": 15},
{ "id": 283, "nombre": "PAUNA","codDep": 15},
{ "id": 284, "nombre": "PAYA","codDep": 15},
{ "id": 285, "nombre": "PAZ DEL RIO","codDep": 15},
{ "id": 286, "nombre": "PESCA","codDep": 15},
{ "id": 287, "nombre": "PISBA","codDep": 15},
{ "id": 288, "nombre": "PUERTO BOYACA","codDep": 15},
{ "id": 289, "nombre": "QUIPAMA","codDep": 15},
{ "id": 290, "nombre": "RAMIRIQUI","codDep": 15},
{ "id": 291, "nombre": "RAQUIRA","codDep": 15},
{ "id": 292, "nombre": "RONDON","codDep": 15},
{ "id": 293, "nombre": "SABOYA","codDep": 15},
{ "id": 294, "nombre": "SACHICA","codDep": 15},
{ "id": 295, "nombre": "SAMACA","codDep": 15},
{ "id": 296, "nombre": "SAN EDUARDO","codDep": 15},
{ "id": 297, "nombre": "SAN JOSE DE PARE","codDep": 15},
{ "id": 298, "nombre": "SAN LUIS DE GACENO","codDep": 15},
{ "id": 299, "nombre": "SAN MATEO","codDep": 15},
{ "id": 300, "nombre": "SAN MIGUEL DE SEMA","codDep": 15},
{ "id": 301, "nombre": "SAN PABLO DE BORBUR","codDep": 15},
{ "id": 302, "nombre": "SANTANA","codDep": 15},
{ "id": 303, "nombre": "SANTA MARIA","codDep": 15},
{ "id": 304, "nombre": "SANTA ROSA DE VITERBO","codDep": 15},
{ "id": 305, "nombre": "SANTA SOFIA","codDep": 15},
{ "id": 306, "nombre": "SATIVANORTE","codDep": 15},
{ "id": 307, "nombre": "SATIVASUR","codDep": 15},
{ "id": 308, "nombre": "SIACHOQUE","codDep": 15},
{ "id": 309, "nombre": "SOATA","codDep": 15},
{ "id": 310, "nombre": "SOCOTA","codDep": 15},
{ "id": 311, "nombre": "SOCHA","codDep": 15},
{ "id": 312, "nombre": "SOGAMOSO","codDep": 15},
{ "id": 313, "nombre": "SOMONDOCO","codDep": 15},
{ "id": 314, "nombre": "SORA","codDep": 15},
{ "id": 315, "nombre": "SOTAQUIRA","codDep": 15},
{ "id": 316, "nombre": "SORACA","codDep": 15},
{ "id": 317, "nombre": "SUSACON","codDep": 15},
{ "id": 318, "nombre": "SUTAMARCHAN","codDep": 15},
{ "id": 319, "nombre": "SUTATENZA","codDep": 15},
{ "id": 320, "nombre": "TASCO","codDep": 15},
{ "id": 321, "nombre": "TENZA","codDep": 15},
{ "id": 322, "nombre": "TIBANA","codDep": 15},
{ "id": 323, "nombre": "TIBASOSA","codDep": 15},
{ "id": 324, "nombre": "TINJACA","codDep": 15},
{ "id": 325, "nombre": "TIPACOQUE","codDep": 15},
{ "id": 326, "nombre": "TOCA","codDep": 15},
{ "id": 327, "nombre": "TOGUI","codDep": 15},
{ "id": 328, "nombre": "TOPAGA","codDep": 15},
{ "id": 329, "nombre": "TOTA","codDep": 15},
{ "id": 330, "nombre": "TUNUNGUA","codDep": 15},
{ "id": 331, "nombre": "TURMEQUE","codDep": 15},
{ "id": 332, "nombre": "TUTA","codDep": 15},
{ "id": 333, "nombre": "TUTASA","codDep": 15},
{ "id": 334, "nombre": "UMBITA","codDep": 15},
{ "id": 335, "nombre": "VENTAQUEMADA","codDep": 15},
{ "id": 336, "nombre": "VIRACACHA","codDep": 15},
{ "id": 337, "nombre": "ZETAQUIRA","codDep": 15},
{ "id": 338, "nombre": "MANIZALES","codDep": 17},
{ "id": 339, "nombre": "AGUADAS","codDep": 17},
{ "id": 340, "nombre": "ANSERMA","codDep": 17},
{ "id": 341, "nombre": "ARANZAZU","codDep": 17},
{ "id": 342, "nombre": "BELALCAZAR","codDep": 17},
{ "id": 343, "nombre": "CHINCHINA","codDep": 17},
{ "id": 344, "nombre": "FILADELFIA","codDep": 17},
{ "id": 345, "nombre": "LA DORADA","codDep": 17},
{ "id": 346, "nombre": "LA MERCED","codDep": 17},
{ "id": 347, "nombre": "MANZANARES","codDep": 17},
{ "id": 348, "nombre": "MARMATO","codDep": 17},
{ "id": 349, "nombre": "MARQUETALIA","codDep": 17},
{ "id": 350, "nombre": "MARULANDA","codDep": 17},
{ "id": 351, "nombre": "NEIRA","codDep": 17},
{ "id": 352, "nombre": "NORCASIA","codDep": 17},
{ "id": 353, "nombre": "PACORA","codDep": 17},
{ "id": 354, "nombre": "PALESTINA","codDep": 17},
{ "id": 355, "nombre": "PENSILVANIA","codDep": 17},
{ "id": 356, "nombre": "RIOSUCIO","codDep": 17},
{ "id": 357, "nombre": "RISARALDA","codDep": 17},
{ "id": 358, "nombre": "SALAMINA","codDep": 17},
{ "id": 359, "nombre": "SAMANA","codDep": 17},
{ "id": 360, "nombre": "SAN JOSE","codDep": 17},
{ "id": 361, "nombre": "SUPIA","codDep": 17},
{ "id": 362, "nombre": "VICTORIA","codDep": 17},
{ "id": 363, "nombre": "VILLAMARIA","codDep": 17},
{ "id": 364, "nombre": "VITERBO","codDep": 17},
{ "id": 365, "nombre": "FLORENCIA","codDep": 18},
{ "id": 366, "nombre": "ALBANIA","codDep": 18},
{ "id": 367, "nombre": "BELEN DE LOS ANDAQUIES","codDep": 18},
{ "id": 368, "nombre": "CARTAGENA DEL CHAIRA","codDep": 18},
{ "id": 369, "nombre": "CURILLO","codDep": 18},
{ "id": 370, "nombre": "EL DONCELLO","codDep": 18},
{ "id": 371, "nombre": "EL PAUJIL","codDep": 18},
{ "id": 372, "nombre": "LA MONTAÑITA","codDep": 18},
{ "id": 373, "nombre": "MILAN","codDep": 18},
{ "id": 374, "nombre": "MORELIA","codDep": 18},
{ "id": 375, "nombre": "PUERTO RICO","codDep": 18},
{ "id": 376, "nombre": "SAN JOSE DE FRAGUA","codDep": 18},
{ "id": 377, "nombre": "SAN VICENTE DEL CAGUAN","codDep": 18},
{ "id": 378, "nombre": "SOLANO","codDep": 18},
{ "id": 379, "nombre": "SOLITA","codDep": 18},
{ "id": 380, "nombre": "VALPARAISO","codDep": 18},
{ "id": 381, "nombre": "POPAYAN","codDep": 19},
{ "id": 382, "nombre": "ALMAGUER","codDep": 19},
{ "id": 383, "nombre": "ARGELIA","codDep": 19},
{ "id": 384, "nombre": "BALBOA","codDep": 19},
{ "id": 385, "nombre": "BOLIVAR","codDep": 19},
{ "id": 386, "nombre": "BUENOS AIRES","codDep": 19},
{ "id": 387, "nombre": "CAJIBIO","codDep": 19},
{ "id": 388, "nombre": "CALDONO","codDep": 19},
{ "id": 389, "nombre": "CALOTO","codDep": 19},
{ "id": 390, "nombre": "CORINTO","codDep": 19},
{ "id": 391, "nombre": "EL TAMBO","codDep": 19},
{ "id": 392, "nombre": "FLORENCIA","codDep": 19},
{ "id": 393, "nombre": "GUAPI","codDep": 19},
{ "id": 394, "nombre": "INZA","codDep": 19},
{ "id": 395, "nombre": "JAMBALO","codDep": 19},
{ "id": 396, "nombre": "LA SIERRA","codDep": 19},
{ "id": 397, "nombre": "LA VEGA","codDep": 19},
{ "id": 398, "nombre": "LOPEZ (MICAY)","codDep": 19},
{ "id": 399, "nombre": "MERCADERES","codDep": 19},
{ "id": 400, "nombre": "MIRANDA","codDep": 19},
{ "id": 401, "nombre": "MORALES","codDep": 19},
{ "id": 402, "nombre": "PADILLA","codDep": 19},
{ "id": 403, "nombre": "PAEZ (BELALCAZAR)","codDep": 19},
{ "id": 404, "nombre": "PATIA (EL BORDO)","codDep": 19},
{ "id": 405, "nombre": "PIAMONTE","codDep": 19},
{ "id": 406, "nombre": "PIENDAMO","codDep": 19},
{ "id": 407, "nombre": "PUERTO TEJADA","codDep": 19},
{ "id": 408, "nombre": "PURACE (COCONUCO)","codDep": 19},
{ "id": 409, "nombre": "ROSAS","codDep": 19},
{ "id": 410, "nombre": "SAN SEBASTIAN","codDep": 19},
{ "id": 411, "nombre": "SANTANDER DE QUILICHAO","codDep": 19},
{ "id": 412, "nombre": "SANTA ROSA","codDep": 19},
{ "id": 413, "nombre": "SILVIA","codDep": 19},
{ "id": 414, "nombre": "SOTARA (PAISPAMBA)","codDep": 19},
{ "id": 415, "nombre": "SUAREZ","codDep": 19},
{ "id": 416, "nombre": "TIMBIO","codDep": 19},
{ "id": 417, "nombre": "TIMBIQUI","codDep": 19},
{ "id": 418, "nombre": "TORIBIO","codDep": 19},
{ "id": 419, "nombre": "TOTORO","codDep": 19},
{ "id": 420, "nombre": "VILLARICA","codDep": 19},
{ "id": 421, "nombre": "VALLEDUPAR","codDep": 20},
{ "id": 422, "nombre": "AGUACHICA","codDep": 20},
{ "id": 423, "nombre": "AGUSTIN CODAZZI","codDep": 20},
{ "id": 424, "nombre": "ASTREA","codDep": 20},
{ "id": 425, "nombre": "BECERRIL","codDep": 20},
{ "id": 426, "nombre": "BOSCONIA","codDep": 20},
{ "id": 427, "nombre": "CHIMICHAGUA","codDep": 20},
{ "id": 428, "nombre": "CHIRIGUANA","codDep": 20},
{ "id": 429, "nombre": "CURUMANI","codDep": 20},
{ "id": 430, "nombre": "EL COPEY","codDep": 20},
{ "id": 431, "nombre": "EL PASO","codDep": 20},
{ "id": 432, "nombre": "GAMARRA","codDep": 20},
{ "id": 433, "nombre": "GONZALEZ","codDep": 20},
{ "id": 434, "nombre": "LA GLORIA","codDep": 20},
{ "id": 435, "nombre": "LA JAGUA IBIRICO","codDep": 20},
{ "id": 436, "nombre": "MANAURE (BALCON DELCESAR)","codDep": 20},
{ "id": 437, "nombre": "PAILITAS","codDep": 20},
{ "id": 438, "nombre": "PELAYA","codDep": 20},
{ "id": 439, "nombre": "PUEBLO BELLO","codDep": 20},
{ "id": 440, "nombre": "RIO DE ORO","codDep": 20},
{ "id": 441, "nombre": "LA PAZ (ROBLES)","codDep": 20},
{ "id": 442, "nombre": "SAN ALBERTO","codDep": 20},
{ "id": 443, "nombre": "SAN DIEGO","codDep": 20},
{ "id": 444, "nombre": "SAN MARTIN","codDep": 20},
{ "id": 445, "nombre": "TAMALAMEQUE","codDep": 20},
{ "id": 446, "nombre": "MONTERIA","codDep": 23},
{ "id": 447, "nombre": "AYAPEL","codDep": 23},
{ "id": 448, "nombre": "BUENAVISTA","codDep": 23},
{ "id": 449, "nombre": "CANALETE","codDep": 23},
{ "id": 450, "nombre": "CERETE","codDep": 23},
{ "id": 451, "nombre": "CHIMA","codDep": 23},
{ "id": 452, "nombre": "CHINU","codDep": 23},
{ "id": 453, "nombre": "CIENAGA DE ORO","codDep": 23},
{ "id": 454, "nombre": "COTORRA","codDep": 23},
{ "id": 455, "nombre": "LA APARTADA","codDep": 23},
{ "id": 456, "nombre": "LORICA","codDep": 23},
{ "id": 457, "nombre": "LOS CORDOBAS","codDep": 23},
{ "id": 458, "nombre": "MOMIL","codDep": 23},
{ "id": 459, "nombre": "MONTELIBANO","codDep": 23},
{ "id": 460, "nombre": "MOÑITOS","codDep": 23},
{ "id": 461, "nombre": "PLANETA RICA","codDep": 23},
{ "id": 462, "nombre": "PUEBLO NUEVO","codDep": 23},
{ "id": 463, "nombre": "PUERTO ESCONDIDO","codDep": 23},
{ "id": 464, "nombre": "PUERTO LIBERTADOR","codDep": 23},
{ "id": 465, "nombre": "PURISIMA","codDep": 23},
{ "id": 466, "nombre": "SAHAGUN","codDep": 23},
{ "id": 467, "nombre": "SAN ANDRES SOTAVENTO","codDep": 23},
{ "id": 468, "nombre": "SAN ANTERO","codDep": 23},
{ "id": 469, "nombre": "SAN BERNARDO DELVIENTO","codDep": 23},
{ "id": 470, "nombre": "SAN CARLOS","codDep": 23},
{ "id": 471, "nombre": "SAN PELAYO","codDep": 23},
{ "id": 472, "nombre": "TIERRALTA","codDep": 23},
{ "id": 473, "nombre": "VALENCIA","codDep": 23},
{ "id": 474, "nombre": "AGUA DE DIOS","codDep": 25},
{ "id": 475, "nombre": "ALBAN","codDep": 25},
{ "id": 476, "nombre": "ANAPOIMA","codDep": 25},
{ "id": 477, "nombre": "ANOLAIMA","codDep": 25},
{ "id": 478, "nombre": "ARBELAEZ","codDep": 25},
{ "id": 479, "nombre": "BELTRAN","codDep": 25},
{ "id": 480, "nombre": "BITUIMA","codDep": 25},
{ "id": 481, "nombre": "BOJACA","codDep": 25},
{ "id": 482, "nombre": "CABRERA","codDep": 25},
{ "id": 483, "nombre": "CACHIPAY","codDep": 25},
{ "id": 484, "nombre": "CAJICA","codDep": 25},
{ "id": 485, "nombre": "CAPARRAPI","codDep": 25},
{ "id": 486, "nombre": "CAQUEZA","codDep": 25},
{ "id": 487, "nombre": "CARMEN DE CARUPA","codDep": 25},
{ "id": 488, "nombre": "CHAGUANI","codDep": 25},
{ "id": 489, "nombre": "CHIA","codDep": 25},
{ "id": 490, "nombre": "CHIPAQUE","codDep": 25},
{ "id": 491, "nombre": "CHOACHI","codDep": 25},
{ "id": 492, "nombre": "CHOCONTA","codDep": 25},
{ "id": 493, "nombre": "COGUA","codDep": 25},
{ "id": 494, "nombre": "COTA","codDep": 25},
{ "id": 495, "nombre": "CUCUNUBA","codDep": 25},
{ "id": 496, "nombre": "EL COLEGIO","codDep": 25},
{ "id": 497, "nombre": "EL PEÑON","codDep": 25},
{ "id": 498, "nombre": "EL ROSAL","codDep": 25},
{ "id": 499, "nombre": "FACATATIVA","codDep": 25},
{ "id": 500, "nombre": "FOMEQUE","codDep": 25},
{ "id": 501, "nombre": "FOSCA","codDep": 25},
{ "id": 502, "nombre": "FUNZA","codDep": 25},
{ "id": 503, "nombre": "FUQUENE","codDep": 25},
{ "id": 504, "nombre": "FUSAGASUGA","codDep": 25},
{ "id": 505, "nombre": "GACHALA","codDep": 25},
{ "id": 506, "nombre": "GACHANCIPA","codDep": 25},
{ "id": 507, "nombre": "GACHETA","codDep": 25},
{ "id": 508, "nombre": "GAMA","codDep": 25},
{ "id": 509, "nombre": "GIRARDOT","codDep": 25},
{ "id": 510, "nombre": "GRANADA","codDep": 25},
{ "id": 511, "nombre": "GUACHETA","codDep": 25},
{ "id": 512, "nombre": "GUADUAS","codDep": 25},
{ "id": 513, "nombre": "GUASCA","codDep": 25},
{ "id": 514, "nombre": "GUATAQUI","codDep": 25},
{ "id": 515, "nombre": "GUATAVITA","codDep": 25},
{ "id": 516, "nombre": "GUAYABAL DE SIQUIMA","codDep": 25},
{ "id": 517, "nombre": "GUAYABETAL","codDep": 25},
{ "id": 518, "nombre": "GUTIERREZ","codDep": 25},
{ "id": 519, "nombre": "JERUSALEN","codDep": 25},
{ "id": 520, "nombre": "JUNIN","codDep": 25},
{ "id": 521, "nombre": "LA CALERA","codDep": 25},
{ "id": 522, "nombre": "LA MESA","codDep": 25},
{ "id": 523, "nombre": "LA PALMA","codDep": 25},
{ "id": 524, "nombre": "LA PEÑA","codDep": 25},
{ "id": 525, "nombre": "LA VEGA","codDep": 25},
{ "id": 526, "nombre": "LENGUAZAQUE","codDep": 25},
{ "id": 527, "nombre": "MACHETA","codDep": 25},
{ "id": 528, "nombre": "MADRID","codDep": 25},
{ "id": 529, "nombre": "MANTA","codDep": 25},
{ "id": 530, "nombre": "MEDINA","codDep": 25},
{ "id": 531, "nombre": "MOSQUERA","codDep": 25},
{ "id": 532, "nombre": "NARIÑO","codDep": 25},
{ "id": 533, "nombre": "NEMOCON","codDep": 25},
{ "id": 534, "nombre": "NILO","codDep": 25},
{ "id": 535, "nombre": "NIMAIMA","codDep": 25},
{ "id": 536, "nombre": "NOCAIMA","codDep": 25},
{ "id": 537, "nombre": "VENECIA (OSPINA PEREZ)","codDep": 25},
{ "id": 538, "nombre": "PACHO","codDep": 25},
{ "id": 539, "nombre": "PAIME","codDep": 25},
{ "id": 540, "nombre": "PANDI","codDep": 25},
{ "id": 541, "nombre": "PARATEBUENO","codDep": 25},
{ "id": 542, "nombre": "PASCA","codDep": 25},
{ "id": 543, "nombre": "PUERTO SALGAR","codDep": 25},
{ "id": 544, "nombre": "PULI","codDep": 25},
{ "id": 545, "nombre": "QUEBRADANEGRA","codDep": 25},
{ "id": 546, "nombre": "QUETAME","codDep": 25},
{ "id": 547, "nombre": "QUIPILE","codDep": 25},
{ "id": 548, "nombre": "APULO (RAFAEL REYES)","codDep": 25},
{ "id": 549, "nombre": "RICAURTE","codDep": 25},
{ "id": 550, "nombre": "SAN ANTONIO DELTEQUENDAMA","codDep": 25},
{ "id": 551, "nombre": "SAN BERNARDO","codDep": 25},
{ "id": 552, "nombre": "SAN CAYETANO","codDep": 25},
{ "id": 553, "nombre": "SAN FRANCISCO","codDep": 25},
{ "id": 554, "nombre": "SAN JUAN DE RIOSECO","codDep": 25},
{ "id": 555, "nombre": "SASAIMA","codDep": 25},
{ "id": 556, "nombre": "SESQUILE","codDep": 25},
{ "id": 557, "nombre": "SIBATE","codDep": 25},
{ "id": 558, "nombre": "SILVANIA","codDep": 25},
{ "id": 559, "nombre": "SIMIJACA","codDep": 25},
{ "id": 560, "nombre": "SOACHA","codDep": 25},
{ "id": 561, "nombre": "SOPO","codDep": 25},
{ "id": 562, "nombre": "SUBACHOQUE","codDep": 25},
{ "id": 563, "nombre": "SUESCA","codDep": 25},
{ "id": 564, "nombre": "SUPATA","codDep": 25},
{ "id": 565, "nombre": "SUSA","codDep": 25},
{ "id": 566, "nombre": "SUTATAUSA","codDep": 25},
{ "id": 567, "nombre": "TABIO","codDep": 25},
{ "id": 568, "nombre": "TAUSA","codDep": 25},
{ "id": 569, "nombre": "TENA","codDep": 25},
{ "id": 570, "nombre": "TENJO","codDep": 25},
{ "id": 571, "nombre": "TIBACUY","codDep": 25},
{ "id": 572, "nombre": "TIBIRITA","codDep": 25},
{ "id": 573, "nombre": "TOCAIMA","codDep": 25},
{ "id": 574, "nombre": "TOCANCIPA","codDep": 25},
{ "id": 575, "nombre": "TOPAIPI","codDep": 25},
{ "id": 576, "nombre": "UBALA","codDep": 25},
{ "id": 577, "nombre": "UBAQUE","codDep": 25},
{ "id": 578, "nombre": "UBATE","codDep": 25},
{ "id": 579, "nombre": "UNE","codDep": 25},
{ "id": 580, "nombre": "UTICA","codDep": 25},
{ "id": 581, "nombre": "VERGARA","codDep": 25},
{ "id": 582, "nombre": "VIANI","codDep": 25},
{ "id": 583, "nombre": "VILLAGOMEZ","codDep": 25},
{ "id": 584, "nombre": "VILLAPINZON","codDep": 25},
{ "id": 585, "nombre": "VILLETA","codDep": 25},
{ "id": 586, "nombre": "VIOTA","codDep": 25},
{ "id": 587, "nombre": "YACOPI","codDep": 25},
{ "id": 588, "nombre": "ZIPACON","codDep": 25},
{ "id": 589, "nombre": "ZIPAQUIRA","codDep": 25},
{ "id": 590, "nombre": "QUIBDO ","codDep": 27},
{ "id": 591, "nombre": "ACANDI","codDep": 27},
{ "id": 592, "nombre": "ALTO BAUDO (PIE DE PATO)","codDep": 27},
{ "id": 593, "nombre": "ATRATO","codDep": 27},
{ "id": 594, "nombre": "BAGADO","codDep": 27},
{ "id": 595, "nombre": "BAHIA SOLANO (MUTIS)","codDep": 27},
{ "id": 596, "nombre": "BAJO BAUDO (PIZARRO)","codDep": 27},
{ "id": 597, "nombre": "BOJAYA (BELLAVISTA)","codDep": 27},
{ "id": 598, "nombre": "CANTON DE SAN PABLO(MANAGRU)","codDep": 27},
{ "id": 599, "nombre": "CONDOTO","codDep": 27},
{ "id": 600, "nombre": "EL CARMEN DE ATRATO","codDep": 27},
{ "id": 601, "nombre": "LITORAL DEL BAJO SANJUAN ","codDep": 27},
{ "id": 602, "nombre": "ISTMINA","codDep": 27},
{ "id": 603, "nombre": "JURADO","codDep": 27},
{ "id": 604, "nombre": "LLORO","codDep": 27},
{ "id": 605, "nombre": "MEDIO ATRATO","codDep": 27},
{ "id": 606, "nombre": "MEDIO BAUDO","codDep": 27},
{ "id": 607, "nombre": "NOVITA","codDep": 27},
{ "id": 608, "nombre": "NUQUI","codDep": 27},
{ "id": 609, "nombre": "RIOQUITO","codDep": 27},
{ "id": 610, "nombre": "RIOSUCIO","codDep": 27},
{ "id": 611, "nombre": "SAN JOSE DEL PALMAR","codDep": 27},
{ "id": 612, "nombre": "SIPI","codDep": 27},
{ "id": 613, "nombre": "TADO","codDep": 27},
{ "id": 614, "nombre": "UNGUIA","codDep": 27},
{ "id": 615, "nombre": "UNION PANAMERICANA","codDep": 27},
{ "id": 616, "nombre": "NEIVA","codDep": 41},
{ "id": 617, "nombre": "ACEVEDO","codDep": 41},
{ "id": 618, "nombre": "AGRADO","codDep": 41},
{ "id": 619, "nombre": "AIPE","codDep": 41},
{ "id": 620, "nombre": "ALGECIRAS","codDep": 41},
{ "id": 621, "nombre": "ALTAMIRA","codDep": 41},
{ "id": 622, "nombre": "BARAYA","codDep": 41},
{ "id": 623, "nombre": "CAMPOALEGRE","codDep": 41},
{ "id": 624, "nombre": "COLOMBIA","codDep": 41},
{ "id": 625, "nombre": "ELIAS","codDep": 41},
{ "id": 626, "nombre": "GARZON","codDep": 41},
{ "id": 627, "nombre": "GIGANTE","codDep": 41},
{ "id": 628, "nombre": "GUADALUPE","codDep": 41},
{ "id": 629, "nombre": "HOBO","codDep": 41},
{ "id": 630, "nombre": "IQUIRA","codDep": 41},
{ "id": 631, "nombre": "ISNOS (SAN JOSE DE ISNOS)","codDep": 41},
{ "id": 632, "nombre": "LA ARGENTINA","codDep": 41},
{ "id": 633, "nombre": "LA PLATA","codDep": 41},
{ "id": 634, "nombre": "NATAGA","codDep": 41},
{ "id": 635, "nombre": "OPORAPA","codDep": 41},
{ "id": 636, "nombre": "PAICOL","codDep": 41},
{ "id": 637, "nombre": "PALERMO","codDep": 41},
{ "id": 638, "nombre": "PALESTINA","codDep": 41},
{ "id": 639, "nombre": "PITAL","codDep": 41},
{ "id": 640, "nombre": "PITALITO","codDep": 41},
{ "id": 641, "nombre": "RIVERA","codDep": 41},
{ "id": 642, "nombre": "SALADOBLANCO","codDep": 41},
{ "id": 643, "nombre": "SAN AGUSTIN","codDep": 41},
{ "id": 644, "nombre": "SANTA MARIA","codDep": 41},
{ "id": 645, "nombre": "SUAZA","codDep": 41},
{ "id": 646, "nombre": "TARQUI","codDep": 41},
{ "id": 647, "nombre": "TESALIA","codDep": 41},
{ "id": 648, "nombre": "TELLO","codDep": 41},
{ "id": 649, "nombre": "TERUEL","codDep": 41},
{ "id": 650, "nombre": "TIMANA","codDep": 41},
{ "id": 651, "nombre": "VILLAVIEJA","codDep": 41},
{ "id": 652, "nombre": "YAGUARA","codDep": 41},
{ "id": 653, "nombre": "RIOHACHA","codDep": 44},
{ "id": 654, "nombre": "BARRANCAS","codDep": 44},
{ "id": 655, "nombre": "DIBULLA","codDep": 44},
{ "id": 656, "nombre": "DISTRACCION","codDep": 44},
{ "id": 657, "nombre": "EL MOLINO","codDep": 44},
{ "id": 658, "nombre": "FONSECA","codDep": 44},
{ "id": 659, "nombre": "HATONUEVO","codDep": 44},
{ "id": 660, "nombre": "LA JAGUA DEL PILAR","codDep": 44},
{ "id": 661, "nombre": "MAICAO","codDep": 44},
{ "id": 662, "nombre": "MANAURE","codDep": 44},
{ "id": 663, "nombre": "SAN JUAN DEL CESAR","codDep": 44},
{ "id": 664, "nombre": "URIBIA","codDep": 44},
{ "id": 665, "nombre": "URUMITA","codDep": 44},
{ "id": 666, "nombre": "VILLANUEVA","codDep": 44},
{ "id": 667, "nombre": "SANTA MARTA","codDep": 47},
{ "id": 668, "nombre": "ALGARROBO","codDep": 47},
{ "id": 669, "nombre": "ARACATACA","codDep": 47},
{ "id": 670, "nombre": "ARIGUANI ","codDep": 47},
{ "id": 671, "nombre": "CERRO SAN ANTONIO","codDep": 47},
{ "id": 672, "nombre": "CHIVOLO","codDep": 47},
{ "id": 673, "nombre": "CIENAGA","codDep": 47},
{ "id": 674, "nombre": "CONCORDIA","codDep": 47},
{ "id": 675, "nombre": "EL BANCO","codDep": 47},
{ "id": 676, "nombre": "EL PIÑON","codDep": 47},
{ "id": 677, "nombre": "EL RETEN","codDep": 47},
{ "id": 678, "nombre": "FUNDACION","codDep": 47},
{ "id": 679, "nombre": "GUAMAL","codDep": 47},
{ "id": 680, "nombre": "PEDRAZA","codDep": 47},
{ "id": 681, "nombre": "PIJIÑO DEL CARMEN","codDep": 47},
{ "id": 682, "nombre": "PIVIJAY","codDep": 47},
{ "id": 683, "nombre": "PLATO","codDep": 47},
{ "id": 684, "nombre": "PUEBLOVIEJO","codDep": 47},
{ "id": 685, "nombre": "REMOLINO","codDep": 47},
{ "id": 686, "nombre": "SABANAS DE SAN ANGEL","codDep": 47},
{ "id": 687, "nombre": "SALAMINA","codDep": 47},
{ "id": 688, "nombre": "SAN SEBASTIAN DE BUENAVISTA","codDep": 47},
{ "id": 689, "nombre": "SAN ZENON","codDep": 47},
{ "id": 690, "nombre": "SANTA ANA","codDep": 47},
{ "id": 691, "nombre": "SITIONUEVO","codDep": 47},
{ "id": 692, "nombre": "TENERIFE","codDep": 47},
{ "id": 693, "nombre": "VILLAVICENCIO","codDep": 50},
{ "id": 694, "nombre": "ACACIAS","codDep": 50},
{ "id": 695, "nombre": "BARRANCA DE UPIA","codDep": 50},
{ "id": 696, "nombre": "CABUYARO","codDep": 50},
{ "id": 697, "nombre": "CASTILLA LA NUEVA","codDep": 50},
{ "id": 698, "nombre": "SAN LUIS DE CUBARRAL","codDep": 50},
{ "id": 699, "nombre": "CUMARAL","codDep": 50},
{ "id": 700, "nombre": "EL CALVARIO","codDep": 50},
{ "id": 701, "nombre": "EL CASTILLO","codDep": 50},
{ "id": 702, "nombre": "EL DORADO","codDep": 50},
{ "id": 703, "nombre": "FUENTE DE ORO","codDep": 50},
{ "id": 704, "nombre": "GRANADA","codDep": 50},
{ "id": 705, "nombre": "GUAMAL","codDep": 50},
{ "id": 706, "nombre": "MAPIRIPAN","codDep": 50},
{ "id": 707, "nombre": "MESETAS","codDep": 50},
{ "id": 708, "nombre": "LA MACARENA","codDep": 50},
{ "id": 709, "nombre": "LA URIBE","codDep": 50},
{ "id": 710, "nombre": "LEJANIAS","codDep": 50},
{ "id": 711, "nombre": "PUERTO CONCORDIA","codDep": 50},
{ "id": 712, "nombre": "PUERTO GAITAN","codDep": 50},
{ "id": 713, "nombre": "PUERTO LOPEZ","codDep": 50},
{ "id": 714, "nombre": "PUERTO LLERAS","codDep": 50},
{ "id": 715, "nombre": "PUERTO RICO","codDep": 50},
{ "id": 716, "nombre": "RESTREPO","codDep": 50},
{ "id": 717, "nombre": "SAN CARLOS DE GUAROA","codDep": 50},
{ "id": 718, "nombre": "SAN JUAN DE ARAMA","codDep": 50},
{ "id": 719, "nombre": "SAN JUANITO","codDep": 50},
{ "id": 720, "nombre": "SAN MARTIN","codDep": 50},
{ "id": 721, "nombre": "VISTAHERMOSA","codDep": 50},
{ "id": 722, "nombre": "PASTO ","codDep": 52},
{ "id": 723, "nombre": "ALBAN (SAN JOSE)","codDep": 52},
{ "id": 724, "nombre": "ALDANA","codDep": 52},
{ "id": 725, "nombre": "ANCUYA","codDep": 52},
{ "id": 726, "nombre": "ARBOLEDA (BERRUECOS)","codDep": 52},
{ "id": 727, "nombre": "BARBACOAS","codDep": 52},
{ "id": 728, "nombre": "BELEN","codDep": 52},
{ "id": 729, "nombre": "BUESACO","codDep": 52},
{ "id": 730, "nombre": "COLON (GENOVA)","codDep": 52},
{ "id": 731, "nombre": "CONSACA","codDep": 52},
{ "id": 732, "nombre": "CONTADERO","codDep": 52},
{ "id": 733, "nombre": "CORDOBA","codDep": 52},
{ "id": 734, "nombre": "CUASPUD (CARLOSAMA)","codDep": 52},
{ "id": 735, "nombre": "CUMBAL","codDep": 52},
{ "id": 736, "nombre": "CUMBITARA","codDep": 52},
{ "id": 737, "nombre": "CHACHAGUI","codDep": 52},
{ "id": 738, "nombre": "EL CHARCO","codDep": 52},
{ "id": 739, "nombre": "EL PEÑOL","codDep": 52},
{ "id": 740, "nombre": "EL ROSARIO","codDep": 52},
{ "id": 741, "nombre": "EL TABLON","codDep": 52},
{ "id": 742, "nombre": "EL TAMBO","codDep": 52},
{ "id": 743, "nombre": "FUNES","codDep": 52},
{ "id": 744, "nombre": "GUACHUCAL","codDep": 52},
{ "id": 745, "nombre": "GUAITARILLA","codDep": 52},
{ "id": 746, "nombre": "GUALMATAN","codDep": 52},
{ "id": 747, "nombre": "ILES","codDep": 52},
{ "id": 748, "nombre": "IMUES","codDep": 52},
{ "id": 749, "nombre": "IPIALES","codDep": 52},
{ "id": 750, "nombre": "LA CRUZ","codDep": 52},
{ "id": 751, "nombre": "LA FLORIDA","codDep": 52},
{ "id": 752, "nombre": "LA LLANADA","codDep": 52},
{ "id": 753, "nombre": "LA TOLA","codDep": 52},
{ "id": 754, "nombre": "LA UNION","codDep": 52},
{ "id": 755, "nombre": "LEIVA","codDep": 52},
{ "id": 756, "nombre": "LINARES","codDep": 52},
{ "id": 757, "nombre": "LOS ANDES (SOTOMAYOR)","codDep": 52},
{ "id": 758, "nombre": "MAGUI (PAYAN)","codDep": 52},
{ "id": 759, "nombre": "MALLAMA (PIEDRANCHA)","codDep": 52},
{ "id": 760, "nombre": "MOSQUERA","codDep": 52},
{ "id": 761, "nombre": "OLAYA HERRERA ","codDep": 52},
{ "id": 762, "nombre": "OSPINA","codDep": 52},
{ "id": 763, "nombre": "FRANCISCO PIZARRO ","codDep": 52},
{ "id": 764, "nombre": "POLICARPA","codDep": 52},
{ "id": 765, "nombre": "POTOSI","codDep": 52},
{ "id": 766, "nombre": "PROVIDENCIA","codDep": 52},
{ "id": 767, "nombre": "PUERRES","codDep": 52},
{ "id": 768, "nombre": "PUPIALES","codDep": 52},
{ "id": 769, "nombre": "RICAURTE","codDep": 52},
{ "id": 770, "nombre": "ROBERTO PAYAN","codDep": 52},
{ "id": 771, "nombre": "SAMANIEGO","codDep": 52},
{ "id": 772, "nombre": "SANDONA","codDep": 52},
{ "id": 773, "nombre": "SAN BERNARDO","codDep": 52},
{ "id": 774, "nombre": "SAN LORENZO","codDep": 52},
{ "id": 775, "nombre": "SAN PABLO","codDep": 52},
{ "id": 776, "nombre": "SAN PEDRO DE CARTAGO","codDep": 52},
{ "id": 777, "nombre": "SANTA BARBARA","codDep": 52},
{ "id": 778, "nombre": "SANTA CRUZ ","codDep": 52},
{ "id": 779, "nombre": "SAPUYES","codDep": 52},
{ "id": 780, "nombre": "TAMINANGO","codDep": 52},
{ "id": 781, "nombre": "TANGUA","codDep": 52},
{ "id": 782, "nombre": "TUMACO","codDep": 52},
{ "id": 783, "nombre": "TUQUERRES","codDep": 52},
{ "id": 784, "nombre": "YACUANQUER","codDep": 52},
{ "id": 785, "nombre": "CUCUTA","codDep": 54},
{ "id": 786, "nombre": "ABREGO","codDep": 54},
{ "id": 787, "nombre": "ARBOLEDAS","codDep": 54},
{ "id": 788, "nombre": "BOCHALEMA","codDep": 54},
{ "id": 789, "nombre": "BUCARASICA","codDep": 54},
{ "id": 790, "nombre": "CACOTA","codDep": 54},
{ "id": 791, "nombre": "CACHIRA","codDep": 54},
{ "id": 792, "nombre": "CHINACOTA","codDep": 54},
{ "id": 793, "nombre": "CHITAGA","codDep": 54},
{ "id": 794, "nombre": "CONVENCION","codDep": 54},
{ "id": 795, "nombre": "CUCUTILLA","codDep": 54},
{ "id": 796, "nombre": "DURANIA","codDep": 54},
{ "id": 797, "nombre": "EL CARMEN","codDep": 54},
{ "id": 798, "nombre": "EL TARRA","codDep": 54},
{ "id": 799, "nombre": "EL ZULIA","codDep": 54},
{ "id": 800, "nombre": "GRAMALOTE","codDep": 54},
{ "id": 801, "nombre": "HACARI","codDep": 54},
{ "id": 802, "nombre": "HERRAN","codDep": 54},
{ "id": 803, "nombre": "LABATECA","codDep": 54},
{ "id": 804, "nombre": "LA ESPERANZA","codDep": 54},
{ "id": 805, "nombre": "LA PLAYA","codDep": 54},
{ "id": 806, "nombre": "LOS PATIOS","codDep": 54},
{ "id": 807, "nombre": "LOURDES","codDep": 54},
{ "id": 808, "nombre": "MUTISCUA","codDep": 54},
{ "id": 809, "nombre": "OCAÑA","codDep": 54},
{ "id": 810, "nombre": "PAMPLONA","codDep": 54},
{ "id": 811, "nombre": "PAMPLONITA","codDep": 54},
{ "id": 812, "nombre": "PUERTO SANTANDER","codDep": 54},
{ "id": 813, "nombre": "RAGONVALIA","codDep": 54},
{ "id": 814, "nombre": "SALAZAR","codDep": 54},
{ "id": 815, "nombre": "SAN CALIXTO","codDep": 54},
{ "id": 816, "nombre": "SAN CAYETANO","codDep": 54},
{ "id": 817, "nombre": "SANTIAGO","codDep": 54},
{ "id": 818, "nombre": "SARDINATA","codDep": 54},
{ "id": 819, "nombre": "SILOS","codDep": 54},
{ "id": 820, "nombre": "TEORAMA","codDep": 54},
{ "id": 821, "nombre": "TIBU","codDep": 54},
{ "id": 822, "nombre": "TOLEDO","codDep": 54},
{ "id": 823, "nombre": "VILLACARO","codDep": 54},
{ "id": 824, "nombre": "VILLA DEL ROSARIO","codDep": 54},
{ "id": 825, "nombre": "ARMENIA","codDep": 63},
{ "id": 826, "nombre": "BUENAVISTA","codDep": 63},
{ "id": 827, "nombre": "CALARCA","codDep": 63},
{ "id": 828, "nombre": "CIRCASIA","codDep": 63},
{ "id": 829, "nombre": "CORDOBA","codDep": 63},
{ "id": 830, "nombre": "FILANDIA","codDep": 63},
{ "id": 831, "nombre": "GENOVA","codDep": 63},
{ "id": 832, "nombre": "LA TEBAIDA","codDep": 63},
{ "id": 833, "nombre": "MONTENEGRO","codDep": 63},
{ "id": 834, "nombre": "PIJAO","codDep": 63},
{ "id": 835, "nombre": "QUIMBAYA","codDep": 63},
{ "id": 836, "nombre": "SALENTO","codDep": 63},
{ "id": 837, "nombre": "PEREIRA","codDep": 66},
{ "id": 838, "nombre": "APIA","codDep": 66},
{ "id": 839, "nombre": "BALBOA","codDep": 66},
{ "id": 840, "nombre": "BELEN DE UMBRIA","codDep": 66},
{ "id": 841, "nombre": "DOS QUEBRADAS","codDep": 66},
{ "id": 842, "nombre": "GUATICA","codDep": 66},
{ "id": 843, "nombre": "LA CELIA","codDep": 66},
{ "id": 844, "nombre": "LA VIRGINIA","codDep": 66},
{ "id": 845, "nombre": "MARSELLA","codDep": 66},
{ "id": 846, "nombre": "MISTRATO","codDep": 66},
{ "id": 847, "nombre": "PUEBLO RICO","codDep": 66},
{ "id": 848, "nombre": "QUINCHIA","codDep": 66},
{ "id": 849, "nombre": "SANTA ROSA DE CABAL","codDep": 66},
{ "id": 850, "nombre": "SANTUARIO","codDep": 66},
{ "id": 851, "nombre": "BUCARAMANGA","codDep": 68},
{ "id": 852, "nombre": "AGUADA","codDep": 68},
{ "id": 853, "nombre": "ALBANIA","codDep": 68},
{ "id": 854, "nombre": "ARATOCA","codDep": 68},
{ "id": 855, "nombre": "BARBOSA","codDep": 68},
{ "id": 856, "nombre": "BARICHARA","codDep": 68},
{ "id": 857, "nombre": "BARRANCABERMEJA","codDep": 68},
{ "id": 858, "nombre": "BETULIA","codDep": 68},
{ "id": 859, "nombre": "BOLIVAR","codDep": 68},
{ "id": 860, "nombre": "CABRERA","codDep": 68},
{ "id": 861, "nombre": "CALIFORNIA","codDep": 68},
{ "id": 862, "nombre": "CAPITANEJO","codDep": 68},
{ "id": 863, "nombre": "CARCASI","codDep": 68},
{ "id": 864, "nombre": "CEPITA","codDep": 68},
{ "id": 865, "nombre": "CERRITO","codDep": 68},
{ "id": 866, "nombre": "CHARALA","codDep": 68},
{ "id": 867, "nombre": "CHARTA","codDep": 68},
{ "id": 868, "nombre": "CHIMA","codDep": 68},
{ "id": 869, "nombre": "CHIPATA","codDep": 68},
{ "id": 870, "nombre": "CIMITARRA","codDep": 68},
{ "id": 871, "nombre": "CONCEPCION","codDep": 68},
{ "id": 872, "nombre": "CONFINES","codDep": 68},
{ "id": 873, "nombre": "CONTRATACION","codDep": 68},
{ "id": 874, "nombre": "COROMORO","codDep": 68},
{ "id": 875, "nombre": "CURITI","codDep": 68},
{ "id": 876, "nombre": "EL CARMEN DE CHUCURY","codDep": 68},
{ "id": 877, "nombre": "EL GUACAMAYO","codDep": 68},
{ "id": 878, "nombre": "EL PEÑON","codDep": 68},
{ "id": 879, "nombre": "EL PLAYON","codDep": 68},
{ "id": 880, "nombre": "ENCINO","codDep": 68},
{ "id": 881, "nombre": "ENCISO","codDep": 68},
{ "id": 882, "nombre": "FLORIAN","codDep": 68},
{ "id": 883, "nombre": "FLORIDABLANCA","codDep": 68},
{ "id": 884, "nombre": "GALAN","codDep": 68},
{ "id": 885, "nombre": "GAMBITA","codDep": 68},
{ "id": 886, "nombre": "GIRON","codDep": 68},
{ "id": 887, "nombre": "GUACA","codDep": 68},
{ "id": 888, "nombre": "GUADALUPE","codDep": 68},
{ "id": 889, "nombre": "GUAPOTA","codDep": 68},
{ "id": 890, "nombre": "GUAVATA","codDep": 68},
{ "id": 891, "nombre": "GUEPSA","codDep": 68},
{ "id": 892, "nombre": "HATO","codDep": 68},
{ "id": 893, "nombre": "JESUS MARIA","codDep": 68},
{ "id": 894, "nombre": "JORDAN","codDep": 68},
{ "id": 895, "nombre": "LA BELLEZA","codDep": 68},
{ "id": 896, "nombre": "LANDAZURI","codDep": 68},
{ "id": 897, "nombre": "LA PAZ","codDep": 68},
{ "id": 898, "nombre": "LEBRIJA","codDep": 68},
{ "id": 899, "nombre": "LOS SANTOS","codDep": 68},
{ "id": 900, "nombre": "MACARAVITA","codDep": 68},
{ "id": 901, "nombre": "MALAGA","codDep": 68},
{ "id": 902, "nombre": "MATANZA","codDep": 68},
{ "id": 903, "nombre": "MOGOTES","codDep": 68},
{ "id": 904, "nombre": "MOLAGAVITA","codDep": 68},
{ "id": 905, "nombre": "OCAMONTE","codDep": 68},
{ "id": 906, "nombre": "OIBA","codDep": 68},
{ "id": 907, "nombre": "ONZAGA","codDep": 68},
{ "id": 908, "nombre": "PALMAR","codDep": 68},
{ "id": 909, "nombre": "PALMAS DEL SOCORRO","codDep": 68},
{ "id": 910, "nombre": "PARAMO","codDep": 68},
{ "id": 911, "nombre": "PIEDECUESTA","codDep": 68},
{ "id": 912, "nombre": "PINCHOTE","codDep": 68},
{ "id": 913, "nombre": "PUENTE NACIONAL","codDep": 68},
{ "id": 914, "nombre": "PUERTO PARRA","codDep": 68},
{ "id": 915, "nombre": "PUERTO WILCHES","codDep": 68},
{ "id": 916, "nombre": "RIONEGRO","codDep": 68},
{ "id": 917, "nombre": "SABANA DE TORRES","codDep": 68},
{ "id": 918, "nombre": "SAN ANDRES","codDep": 68},
{ "id": 919, "nombre": "SAN BENITO","codDep": 68},
{ "id": 920, "nombre": "SAN GIL","codDep": 68},
{ "id": 921, "nombre": "SAN JOAQUIN","codDep": 68},
{ "id": 922, "nombre": "SAN JOSE DE MIRANDA","codDep": 68},
{ "id": 923, "nombre": "SAN MIGUEL","codDep": 68},
{ "id": 924, "nombre": "SAN VICENTE DE CHUCURI","codDep": 68},
{ "id": 925, "nombre": "SANTA BARBARA","codDep": 68},
{ "id": 926, "nombre": "SANTA HELENA DEL OPON","codDep": 68},
{ "id": 927, "nombre": "SIMACOTA","codDep": 68},
{ "id": 928, "nombre": "SOCORRO","codDep": 68},
{ "id": 929, "nombre": "SUAITA","codDep": 68},
{ "id": 930, "nombre": "SUCRE","codDep": 68},
{ "id": 931, "nombre": "SURATA","codDep": 68},
{ "id": 932, "nombre": "TONA","codDep": 68},
{ "id": 933, "nombre": "VALLE SAN JOSE","codDep": 68},
{ "id": 934, "nombre": "VELEZ","codDep": 68},
{ "id": 935, "nombre": "VETAS","codDep": 68},
{ "id": 936, "nombre": "VILLANUEVA","codDep": 68},
{ "id": 937, "nombre": "ZAPATOCA","codDep": 68},
{ "id": 938, "nombre": "SINCELEJO","codDep": 70},
{ "id": 939, "nombre": "BUENAVISTA","codDep": 70},
{ "id": 940, "nombre": "CAIMITO","codDep": 70},
{ "id": 941, "nombre": "COLOSO (RICAURTE)","codDep": 70},
{ "id": 942, "nombre": "COROZAL","codDep": 70},
{ "id": 943, "nombre": "CHALAN","codDep": 70},
{ "id": 944, "nombre": "GALERAS ","codDep": 70},
{ "id": 945, "nombre": "GUARANDA","codDep": 70},
{ "id": 946, "nombre": "LA UNION","codDep": 70},
{ "id": 947, "nombre": "LOS PALMITOS","codDep": 70},
{ "id": 948, "nombre": "MAJAGUAL","codDep": 70},
{ "id": 949, "nombre": "MORROA","codDep": 70},
{ "id": 950, "nombre": "OVEJAS","codDep": 70},
{ "id": 951, "nombre": "PALMITO","codDep": 70},
{ "id": 952, "nombre": "SAMPUES","codDep": 70},
{ "id": 953, "nombre": "SAN BENITO ABAD","codDep": 70},
{ "id": 954, "nombre": "SAN JUAN DE BETULIA","codDep": 70},
{ "id": 955, "nombre": "SAN MARCOS","codDep": 70},
{ "id": 956, "nombre": "SAN ONOFRE","codDep": 70},
{ "id": 957, "nombre": "SAN PEDRO","codDep": 70},
{ "id": 958, "nombre": "SINCE","codDep": 70},
{ "id": 959, "nombre": "SUCRE","codDep": 70},
{ "id": 960, "nombre": "TOLU","codDep": 70},
{ "id": 961, "nombre": "TOLUVIEJO","codDep": 70},
{ "id": 962, "nombre": "IBAGUE","codDep": 73},
{ "id": 963, "nombre": "ALPUJARRA","codDep": 73},
{ "id": 964, "nombre": "ALVARADO","codDep": 73},
{ "id": 965, "nombre": "AMBALEMA","codDep": 73},
{ "id": 966, "nombre": "ANZOATEGUI","codDep": 73},
{ "id": 967, "nombre": "ARMERO (GUAYABAL)","codDep": 73},
{ "id": 968, "nombre": "ATACO","codDep": 73},
{ "id": 969, "nombre": "CAJAMARCA","codDep": 73},
{ "id": 970, "nombre": "CARMEN APICALA","codDep": 73},
{ "id": 971, "nombre": "CASABIANCA","codDep": 73},
{ "id": 972, "nombre": "CHAPARRAL","codDep": 73},
{ "id": 973, "nombre": "COELLO","codDep": 73},
{ "id": 974, "nombre": "COYAIMA","codDep": 73},
{ "id": 975, "nombre": "CUNDAY","codDep": 73},
{ "id": 976, "nombre": "DOLORES","codDep": 73},
{ "id": 977, "nombre": "ESPINAL","codDep": 73},
{ "id": 978, "nombre": "FALAN","codDep": 73},
{ "id": 979, "nombre": "FLANDES","codDep": 73},
{ "id": 980, "nombre": "FRESNO","codDep": 73},
{ "id": 981, "nombre": "GUAMO","codDep": 73},
{ "id": 982, "nombre": "HERVEO","codDep": 73},
{ "id": 983, "nombre": "HONDA","codDep": 73},
{ "id": 984, "nombre": "ICONONZO","codDep": 73},
{ "id": 985, "nombre": "LERIDA","codDep": 73},
{ "id": 986, "nombre": "LIBANO","codDep": 73},
{ "id": 987, "nombre": "MARIQUITA","codDep": 73},
{ "id": 988, "nombre": "MELGAR","codDep": 73},
{ "id": 989, "nombre": "MURILLO","codDep": 73},
{ "id": 990, "nombre": "NATAGAIMA","codDep": 73},
{ "id": 991, "nombre": "ORTEGA","codDep": 73},
{ "id": 992, "nombre": "PALOCABILDO","codDep": 73},
{ "id": 993, "nombre": "PIEDRAS","codDep": 73},
{ "id": 994, "nombre": "PLANADAS","codDep": 73},
{ "id": 995, "nombre": "PRADO","codDep": 73},
{ "id": 996, "nombre": "PURIFICACION","codDep": 73},
{ "id": 997, "nombre": "RIOBLANCO","codDep": 73},
{ "id": 998, "nombre": "RONCESVALLES","codDep": 73},
{ "id": 999, "nombre": "ROVIRA","codDep": 73},
{ "id": 1000, "nombre": "SALDAÑA","codDep": 73},
{ "id": 1001, "nombre": "SAN ANTONIO","codDep": 73},
{ "id": 1002, "nombre": "SAN LUIS","codDep": 73},
{ "id": 1003, "nombre": "SANTA ISABEL","codDep": 73},
{ "id": 1004, "nombre": "SUAREZ","codDep": 73},
{ "id": 1005, "nombre": "VALLE DE SAN JUAN","codDep": 73},
{ "id": 1006, "nombre": "VENADILLO","codDep": 73},
{ "id": 1007, "nombre": "VILLAHERMOSA","codDep": 73},
{ "id": 1008, "nombre": "VILLARRICA","codDep": 73},
{ "id": 1009, "nombre": "CALI (SANTIAGO DE CALI)","codDep": 76},
{ "id": 1010, "nombre": "ALCALA","codDep": 76},
{ "id": 1011, "nombre": "ANDALUCIA","codDep": 76},
{ "id": 1012, "nombre": "ANSERMANUEVO","codDep": 76},
{ "id": 1013, "nombre": "ARGELIA","codDep": 76},
{ "id": 1014, "nombre": "BOLIVAR","codDep": 76},
{ "id": 1015, "nombre": "BUENAVENTURA","codDep": 76},
{ "id": 1016, "nombre": "BUGA","codDep": 76},
{ "id": 1017, "nombre": "BUGALAGRANDE","codDep": 76},
{ "id": 1018, "nombre": "CAICEDONIA","codDep": 76},
{ "id": 1019, "nombre": "CALIMA (DARIEN)","codDep": 76},
{ "id": 1020, "nombre": "CANDELARIA","codDep": 76},
{ "id": 1021, "nombre": "CARTAGO","codDep": 76},
{ "id": 1022, "nombre": "DAGUA","codDep": 76},
{ "id": 1023, "nombre": "EL AGUILA","codDep": 76},
{ "id": 1024, "nombre": "EL CAIRO","codDep": 76},
{ "id": 1025, "nombre": "EL CERRITO","codDep": 76},
{ "id": 1026, "nombre": "EL DOVIO","codDep": 76},
{ "id": 1027, "nombre": "FLORIDA","codDep": 76},
{ "id": 1028, "nombre": "GINEBRA","codDep": 76},
{ "id": 1029, "nombre": "GUACARI","codDep": 76},
{ "id": 1030, "nombre": "JAMUNDI","codDep": 76},
{ "id": 1031, "nombre": "LA CUMBRE","codDep": 76},
{ "id": 1032, "nombre": "LA UNION","codDep": 76},
{ "id": 1033, "nombre": "LA VICTORIA","codDep": 76},
{ "id": 1034, "nombre": "OBANDO","codDep": 76},
{ "id": 1035, "nombre": "PALMIRA","codDep": 76},
{ "id": 1036, "nombre": "PRADERA","codDep": 76},
{ "id": 1037, "nombre": "RESTREPO","codDep": 76},
{ "id": 1038, "nombre": "RIOFRIO","codDep": 76},
{ "id": 1039, "nombre": "ROLDANILLO","codDep": 76},
{ "id": 1040, "nombre": "SAN PEDRO","codDep": 76},
{ "id": 1041, "nombre": "SEVILLA","codDep": 76},
{ "id": 1042, "nombre": "TORO","codDep": 76},
{ "id": 1043, "nombre": "TRUJILLO","codDep": 76},
{ "id": 1044, "nombre": "TULUA","codDep": 76},
{ "id": 1045, "nombre": "ULLOA","codDep": 76},
{ "id": 1046, "nombre": "VERSALLES","codDep": 76},
{ "id": 1047, "nombre": "VIJES","codDep": 76},
{ "id": 1048, "nombre": "YOTOCO","codDep": 76},
{ "id": 1049, "nombre": "YUMBO","codDep": 76},
{ "id": 1050, "nombre": "ZARZAL","codDep": 76},
{ "id": 1051, "nombre": "ARAUCA","codDep": 81},
{ "id": 1052, "nombre": "ARAUQUITA","codDep": 81},
{ "id": 1053, "nombre": "CRAVO NORTE","codDep": 81},
{ "id": 1054, "nombre": "FORTUL","codDep": 81},
{ "id": 1055, "nombre": "PUERTO RONDON","codDep": 81},
{ "id": 1056, "nombre": "SARAVENA","codDep": 81},
{ "id": 1057, "nombre": "TAME","codDep": 81},
{ "id": 1058, "nombre": "YOPAL","codDep": 85},
{ "id": 1059, "nombre": "AGUAZUL","codDep": 85},
{ "id": 1060, "nombre": "CHAMEZA","codDep": 85},
{ "id": 1061, "nombre": "HATO COROZAL","codDep": 85},
{ "id": 1062, "nombre": "LA SALINA","codDep": 85},
{ "id": 1063, "nombre": "MANI","codDep": 85},
{ "id": 1064, "nombre": "MONTERREY","codDep": 85},
{ "id": 1065, "nombre": "NUNCHIA","codDep": 85},
{ "id": 1066, "nombre": "OROCUE","codDep": 85},
{ "id": 1067, "nombre": "PAZ DE ARIPORO","codDep": 85},
{ "id": 1068, "nombre": "PORE","codDep": 85},
{ "id": 1069, "nombre": "RECETOR","codDep": 85},
{ "id": 1070, "nombre": "SABANALARGA","codDep": 85},
{ "id": 1071, "nombre": "SACAMA","codDep": 85},
{ "id": 1072, "nombre": "SAN LUIS DE PALENQUE","codDep": 85},
{ "id": 1073, "nombre": "TAMARA","codDep": 85},
{ "id": 1074, "nombre": "TAURAMENA","codDep": 85},
{ "id": 1075, "nombre": "TRINIDAD","codDep": 85},
{ "id": 1076, "nombre": "VILLANUEVA","codDep": 85},
{ "id": 1077, "nombre": "MOCOA","codDep": 86},
{ "id": 1078, "nombre": "COLON","codDep": 86},
{ "id": 1079, "nombre": "ORITO","codDep": 86},
{ "id": 1080, "nombre": "PUERTO ASIS","codDep": 86},
{ "id": 1081, "nombre": "PUERTO CAICEDO","codDep": 86},
{ "id": 1082, "nombre": "PUERTO GUZMAN","codDep": 86},
{ "id": 1083, "nombre": "PUERTO LEGUIZAMO","codDep": 86},
{ "id": 1084, "nombre": "SIBUNDOY","codDep": 86},
{ "id": 1085, "nombre": "SAN FRANCISCO","codDep": 86},
{ "id": 1086, "nombre": "SAN MIGUEL (LA DORADA)","codDep": 86},
{ "id": 1087, "nombre": "SANTIAGO","codDep": 86},
{ "id": 1088, "nombre": "LA HORMIGA ","codDep": 86},
{ "id": 1089, "nombre": "VILLAGARZON","codDep": 86},
{ "id": 1090, "nombre": "SAN ANDRES","codDep": 88},
{ "id": 1091, "nombre": "PROVIDENCIA","codDep": 88},
{ "id": 1092, "nombre": "LETICIA","codDep": 91},
{ "id": 1093, "nombre": "EL ENCANTO","codDep": 91},
{ "id": 1094, "nombre": "LA CHORRERA","codDep": 91},
{ "id": 1095, "nombre": "LA PEDRERA","codDep": 91},
{ "id": 1096, "nombre": "LA VICTORIA","codDep": 91},
{ "id": 1097, "nombre": "MIRITI-PARANA","codDep": 91},
{ "id": 1098, "nombre": "PUERTO ALEGRIA","codDep": 91},
{ "id": 1099, "nombre": "PUERTO ARICA","codDep": 91},
{ "id": 1100, "nombre": "PUERTO NARIÑO","codDep": 91},
{ "id": 1101, "nombre": "PUERTO SANTANDER","codDep": 91},
{ "id": 1102, "nombre": "TARAPACA","codDep": 91},
{ "id": 1103, "nombre": "PUERTO INIRIDA","codDep": 94},
{ "id": 1104, "nombre": "BARRANCO MINAS","codDep": 94},
{ "id": 1105, "nombre": "SAN FELIPE","codDep": 94},
{ "id": 1106, "nombre": "PUERTO COLOMBIA","codDep": 94},
{ "id": 1107, "nombre": "LA GUADALUPE","codDep": 94},
{ "id": 1108, "nombre": "CACAHUAL","codDep": 94},
{ "id": 1109, "nombre": "PANA PANA ","codDep": 94},
{ "id": 1110, "nombre": "MORICHAL ","codDep": 94},
{ "id": 1111, "nombre": "SAN JOSE DEL GUAVIARE","codDep": 95},
{ "id": 1112, "nombre": "CALAMAR","codDep": 95},
{ "id": 1113, "nombre": "EL RETORNO","codDep": 95},
{ "id": 1114, "nombre": "MIRAFLORES","codDep": 95},
{ "id": 1115, "nombre": "MITU","codDep": 97},
{ "id": 1116, "nombre": "CARURU","codDep": 97},
{ "id": 1117, "nombre": "PACOA","codDep": 97},
{ "id": 1118, "nombre": "TARAIRA","codDep": 97},
{ "id": 1119, "nombre": "PAPUNAUA (MORICHAL)","codDep": 97},
{ "id": 1120, "nombre": "YAVARATE","codDep": 97},
{ "id": 1121, "nombre": "PUERTO CARREÑO","codDep": 99},
{ "id": 1122, "nombre": "LA PRIMAVERA","codDep": 99},
{ "id": 1123, "nombre": "SANTA RITA","codDep": 99},
{ "id": 1124, "nombre": "SANTA ROSALIA","codDep": 99},
{ "id": 1125, "nombre": "SAN JOSE DE OCUNE","codDep": 99},
{ "id": 1126, "nombre": "CUMARIBO","codDep": 99},

]